
    create table taxon (
       id int4 generated by default as identity,
        authorship varchar(50),
        extinct boolean not null,
        name_canonical varchar(50) not null,
        num_descendants int8 not null,
        num_occurrences int8 not null,
        path varchar(50)[] not null,
        primary key (id)
    );
CREATE INDEX taxon_path_gin_idx ON taxon USING GIN (path);
