server:
  error:
    include-message: always
spring:
  jmx:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: development | testing
  graphql:
    graphiql:
      enabled: true
    cors:
      allowed-origins: "*"
    schema:
      printer:
        enabled: true
---
spring:
  config:
    activate:
      on-profile: development
---
spring:
  config:
    activate:
      on-profile: testing
---
spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/gat
    username: gat
    password: gat
---
spring:
  config:
    activate:
      on-profile: local-docker
  r2dbc:
    url: r2dbc:postgresql://localhost:8081/gat
    username: gat
    password: db_role_gat_pw
---
spring:
  config:
    activate:
      on-profile: external
  r2dbc:
    url: r2dbc:postgresql://${BE_HOST}:${BE_PORT}/${BE_DB}
    username: ${BE_DB_USER}
    password: ${BE_DB_PW}
---
spring:
  config:
    activate:
      on-profile: production | staging
    import: secret-properties-docker.yaml
  r2dbc:
    url: r2dbc:postgresql://${BE_HOST}:${BE_PORT}/${BE_DB}
    username: ${BE_DB_USER}
    password: ${BE_DB_PW}